config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :podcasts, only: [:show, :edit, :update, :create, :new]

  resources :episodes, only: [:edit, :update, :create, :new, :destroy] do
    patch :go_live
  end

  resources :help, only: [:index]

  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :user
  validates_presence_of :user_id, :title, :subtitle, :summary, :audio_link, :image_link, :length, :duration
  validate :duration_format, :length_format
  default_scope { order("created_at ASC") }

  def duration_format
    if duration !~ /\d:\d\d/
      errors.add(:duration, "Duration must be formatted as either HH:MM:SS, H:MM:SS, MM:SS, or M:SS")
    end
  end

  def length_format
    if length.to_i.to_s != length
      errors.add(:length, "Its gotta be a number buddy, I can't believe I'm writing validations for this")
    end
  end
end

app/models/podcast.rb
class Podcast < ApplicationRecord
  belongs_to :user
  validates_presence_of :user_id, :title, :website, :copyright, :subtitle, :summary, :description, :username, :category, :image_link

  def configured?
    title.present? && website.present? && copyright.present? && subtitle.present? && summary.present? && description.present? && username.present? && category.present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :episodes
  has_one :podcast

  def first_non_live_episode
    episodes.where(live: false).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :authorize, :except => [:new, :create, :go_live]

  def new
    @user = current_user
    @episode = Episode.new
    @episode.image_link = current_user.podcast.image_link if current_user.podcast.present?
  end

  def create
    @user = current_user
    @episode = Episode.new(params[:episode].permit(:title, :subtitle, :summary, :audio_link, :image_link, :length, :duration, :live))
    @episode.live = false unless current_user.episodes.last&.live?
    @episode.user = current_user
    if @episode.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @episode = Episode.find(params[:id])
  end

  def update
    @episode = Episode.find(params[:id])
    if @episode.update_attributes(params[:episode].permit(:title, :subtitle, :summary, :audio_link, :image_link, :length, :duration))
        redirect_to root_path
    else
        render 'edit'
    end
  end

  def destroy
    @episode = Episode.find(params[:id])
    @episode.destroy
    redirect_to root_path
  end

  def go_live
    episode = Episode.find(params[:episode_id])
    episode.live = true
    episode.save
    redirect_to user_path(current_user)
  end

  private
  def authorize
    if Episode.find(params[:id]).user != current_user
      redirect_to root_path
    end
  end
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
  def index
  end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  before_filter :authenticate_user!, :except => :show
  before_filter :authorize, :except => [:show, :new, :create]

  def edit
    @podcast = Podcast.find(params[:id])
  end

  def update
    @podcast = Podcast.find(params[:id])
    if @podcast.update_attributes(params[:podcast].permit(:title, :website, :copyright, :subtitle, :summary, :description, :username, :category, :explicit, :image_link))
        redirect_to root_path
    else
        render 'edit'
    end
  end

  def show
    @podcast = Podcast.find(params[:id])
    @episodes = @podcast.user.episodes.where(live: true)
    respond_to do |format|
      format.html
      format.xml
    end
  end

  def new
    @podcast = Podcast.new
  end

  def create
    @user = current_user
    @podcast = Podcast.new(params[:podcast].permit(:title, :website, :copyright, :subtitle, :summary, :description, :username, :category, :explicit, :image_link))
    @podcast.user = current_user
    if @podcast.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  private
  def authorize
    if Podcast.find(params[:id]).user != current_user
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @podcast = current_user.podcast
    @episodes = current_user.episodes
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    if user_signed_in?
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def url_formatter(url)
    url.gsub(/https:\/\//, 'http://')
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/episodes/_form.html.erb
<%= link_to('Confused about how to fill out this form? Read this first', help_index_path) %>
<br><br>
<form id="js-archive-populate">
  <b>Archive.org Link</b><br>
  <input type="text" name="js-archive-link">
  <input type="submit" value="Populate Values">
</form>
<p>Note: it may take a few minutes for the episode to get into the Archive.org API after you upload it. Be patient. Go for a walk.</p>
<div id="js-archive-warning"></div>
<br>
<%= semantic_form_for @episode, :html => { :class => "episode_form" } do |f| %>
  <%= f.inputs do %>
    <%= f.input :title %>
    <%= f.input :subtitle %>
    <%= f.input :summary %>
    <%= f.input :audio_link %>
    <%= f.input :image_link %>
    <%= f.input :length %>
    <%= f.input :duration %>
    <% if @episode.new_record? && current_user.episodes.last&.live? %>
      <%= f.input :live, :label => 'Release episode now' %>
    <% end %>
  <% end %>
  <%= f.actions do %>
    <%= f.action :submit, :as => :button %>
    <%= f.action :cancel, :as => :link %>
  <% end %>
<% end %>

app/views/episodes/edit.html.erb
<h3>Edit episode</h3>
<%= render 'form' %>
<%= link_to 'Delete Episode', @episode, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/episodes/new.html.erb
<h3>Create new episode</h3>
<%= render 'form' %>

app/views/help/index.html.erb
<h3>account setup:</h3>
<ol>
  <li>Create a podcarp account</li>
  <li>Update your podcast settings, all fields must be filled in</li>
  <li>Add a new podcast episode, all fields must be filled in (look at <a href='/podcasts/1' target='_blank'>my sample podcast</a> for reference if you get confused)</li>
  <ul>
    <li>.mp3, .aac, .mp4, .m4p, .m4r, .3gp should all work, but .m4a is going to be the best quality at the smallest size (which means people can download it faster and it costs me less money to maintain this site)</li>
  </ul>
  <li>Click “View XML Feed”</li>
  <li>Copy the URL, that is your podcast feed!</li>
  <li>Go to <a href='http://validator.w3.org/feed/' target='_blank'>validator.w3.org/feed</a> and validate your feed. You should see “This is a valid RSS feed”</li>
  <li>Go to <a href='https://podcastsconnect.apple.com' target='_blank'>podcastsconnect.apple.com</a> and sign in with an apple id</li>
  <li>Click the + button on the top left</li>
  <li>Enter your podcast and click validate</li>
  <li>Click submit!</li>
  <li>You should get an email from Apple once your podcast has been added to the store</li>
</ol>

<h3>adding episodes</h3>
<ol>
  <li>Create account at <a href='https://archive.org/' target='_blank'>archive.org:</a></li>
  <li>Click the upload button at the top of the screen</li>
  <li>Click ‘Upload Files’</li>
  <li>Drag and drop your file into the box area</li>
  <li>Fill in Description and Subject. These don’t matter, but they’re required</li>
  <li>It might take a minute to upload. Don’t complain, it is free.</li>
  <li>Click “Go To Your Page”</li>
  <li>Copy the url from the top of the page. It should look like <i>https://archive.org/details/identifier</i></li>
  <li>On the <a href='/episodes/new'>create new episode</a> page at Podcarp.com, paste the link into the <b>Archive.org Link</b> field and click <b>Populate Values</b>. This may take a minute.</li>
  <li>Fill in Title, Subtitle, and Summary fields. Click 'Create Episode'</li>
</ol>

<h3>adding image to podcast/episode</h3>
<ol>
  <li>Image must be a jpg or jpeg and be 1400x1400 pixels</li>
  <li>Upload file to <a href='https://archive.org/' target='_blank'>archive.org:</a> (just like episodes)</li>
  <li>Click "Show all files"</li>
  <li>Your image file should be near the top, right click on it and select "Copy Link Address"</li>
  <li>Paste this into the Image Link field</li>
</ol>

<h3>about podcarp</h3>
<p>Podcarp was built by Brian Fu and Michael Ramuta in 2017</p>
<p>Podcarp is a totally free service. Feel free to buy either of us a beer if you feel grateful and are in Chicago</p>
<p>If you have any issues with the app, email michaelramuta@gmail.com</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>podcarp</title>
    <meta property="og:url"                content="http://www.podcarp.com/" />
    <meta property="og:type"               content="website" />
    <meta property="og:title"              content="Podcarp: Free & Simple Podcast Hosting" />
    <meta property="og:description"        content="Host your podcast for free. Really. Okay, if your podcast becomes super successful it might not be able to handle all your downloads. Good luck with that though." />
    <meta property="og:image"              content="<%=asset_url('fb_image.jpg') %>" />

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href="/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" media="all">
  </head>

  <body>
    <%= render partial: '/navbar' %>
    <div class='column row'>
      <%= yield %>
    </div>
    <div class="row">
      <div class="medium-12 columns">
        <p class="text-center"><%= notice %></p>
      </div>
    </div>
    <div class="row">
      <div class="medium-12 columns">
        <p class="text-center"><%= alert %></p>
      </div>
    </div>
  </body>
</html>

app/views/podcasts/_form.html.erb
<%= link_to('Confused about how to fill out this form? Read this first', help_index_path) %>
<%= semantic_form_for @podcast do |f| %>
  <%= f.inputs do %>
    <%= f.input :title %>
    <%= f.input :website %>
    <%= f.input :category, :as => :select, :collection => ['Arts', 'Business', 'Comedy', 'Education', 'Games & Hobbies', 'Government & Organizations', 'Health', 'Kids & Family', 'Music', 'News & Politics', 'Religion & Spirituality', 'Science & Medicine', 'Society & Culture', 'Sports & Recreation', 'Technology', 'TV & Film'] %>
    <%= f.input :copyright %>
    <%= f.input :subtitle %>
    <%= f.input :summary %>
    <%= f.input :description %>
    <%= f.input :username %>
    <%= f.input :explicit %>
    <%= f.input :image_link %>
  <% end %>
  <%= f.actions do %>
    <%= f.action :submit, :as => :button %>
    <%= f.action :cancel, :as => :link %>
  <% end %>
<% end %>

app/views/podcasts/edit.html.erb
<h3>Edit Podcast</h3>
<%= render 'form' %>

app/views/podcasts/new.html.erb
<h3>Create Podcast</h3>
<%= render 'form' %>

app/views/podcasts/show.html.erb
<h3>Podcast Info</h1>
<ul>
  <li>Title: <%= @podcast.title %></li>
  <li>Copyright: <%= @podcast.copyright %></li>
  <li>Author: <%= @podcast.username %></li>
  <li>Summary: <%= @podcast.summary %></li>
  <li>Description: <%= @podcast.description %></li>
  <li>Image Link: <a href="<%= @podcast.image_link %>"><%= @podcast.image_link %></a></li>
  <li>Category: <%= @podcast.category %></li>
  <li>Explicit: <%= @podcast.explicit ? 'Yes' : 'No' %></li>
</ul>
<br>
<h3>Episodes</h1>
<ol>
  <% @episodes.each_with_index do |episode, index| %>
    <li><%= episode.title %></li>
    <ul>
      <li>Subtitle: <%= episode.subtitle %></li>
      <li>Summary: <%= episode.summary %></li>
      <li>Episode Image: <a href="<%= episode.image_link %>"><%= episode.image_link %></a></li>
      <li>Length: <%= episode.length.gsub(/\D/, '') %></li>
      <li>Duration: <%= episode.duration %></li>
      <li>Audio Link: <a href="<%= episode.audio_link %>"><%= episode.audio_link %></a></li>
    </ul>
    <br>
  <% end %>
</ol>

app/views/users/show.html.erb
<% if current_user.podcast.nil? %>
  <p><%= link_to('Create your podcast!', new_podcast_path(current_user.podcast)) %></p>
<% else %>
  <h3>Podcast Info</h1>
  <ul>
    <li>Title: <%= @podcast.title %></li>
    <li>Copyright: <%= @podcast.copyright %></li>
    <li>Author: <%= @podcast.username %></li>
    <li>Summary: <%= @podcast.summary %></li>
    <li>Description: <%= @podcast.description %></li>
    <li>Image Link: <a href="<%= @podcast.image_link %>"><%= @podcast.image_link %></a></li>
    <li>Category: <%= @podcast.category %></li>
    <li>Explicit: <%= @podcast.explicit ? 'Yes' : 'No' %></li>
  </ul>
  <br>
    <div class='row small-up-1 medium-up-2 large-up-3'>
      <% @episodes.each_with_index do |episode, index| %>
      <div class='column'>
        <div class='card'>
          <div class='card-divider'>
            <h4>
              <%= episode.title %>
            </h4>
          </div>
          <div class='card-section'>
            <% if !episode.live? %>
              <strong>EPISODE NOT LIVE</Strong>
              <% if current_user.first_non_live_episode == episode %>
                - <%= link_to('Push Live Now', episode_go_live_path(episode), method: 'patch') %>
              <% end %>
            <% end %>
            <dl>
              <dt>Subtitle</dt>
              <dd><%= episode.subtitle %></dd>
              <dt>Summary</dt>
              <dd><%= episode.summary %></dd>
              <dt>Episode Image</dt>
              <dd><a href="<%= episode.image_link %>"><%= episode.image_link %></a></dd>
              <dt>Length</dt>
              <dd><%= episode.length.gsub(/\D/, '') %></dd>
              <dt>Duration</dt>
              <dd><%= episode.duration %></dd>
              <dt>Audio Link</dt>
              <dd><a href="<%= episode.audio_link %>"><%= episode.audio_link %></a></dd>
            </dl>
            <%= link_to edit_episode_path(episode) do %>
              <i class="fa fa-pencil fa-2x hvr-rotate float-right"></i>
            <% end %>
            <br>
          </div>
        </div>
      </div>
      <% end %>
    </div>
<% end %>
<%= link_to new_episode_path, class: 'new-episode' do %>
  <i class="fa fa-plus fa-2x fa-inverse hvr-icon-grow"></i>
<% end %>

app/views/welcome/index.html.erb
<p>Welcome To Podcarp! Yes, this is actually a free service to host podcasts. Really. Okay, if your podcast becomes super successful it might not be able to handle all your downloads. Good luck with that though.</p>

<p><%= link_to('Log In', new_user_session_path) %></p>
<p><%= link_to('Sign Up', new_user_registration_path) %></p>